// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.GameView = (function(_super) {
  __extends(GameView, _super);

  function GameView() {
    return GameView.__super__.constructor.apply(this, arguments);
  }

  GameView.prototype.template = _.template('<h1>Welcome to Blackjack</h2> <div id="menu" style="float:left; height:100%; width:150px;"> <h2 style="margin-bottom:5px">Player</h2> <span>Wins: <span id="playerWins">0</span></span> <h2 style="margin-bottom:5px">Dealer</h2> <span>Wins: <span id="dealerWins">0</span></span> </div> <div id="gameBoard" style="margin:auto 20px"></div>');

  GameView.prototype.initialize = function() {
    return this.render();
  };

  GameView.prototype.render = function() {
    this.$el.children().detach();
    return this.$el.html(this.template());
  };

  return GameView;

})(Backbone.View);
