// Generated by CoffeeScript 1.8.0
var blackjackApp;

blackjackApp = new App();

new GameView({
  model: blackjackApp
}).$el.appendTo('body');

new AppView({
  model: blackjackApp
}).$el.appendTo('#gameBoard');
